export const domainEventTypes = {
  BOOKING_CREATED: "BOOKING_CREATED",
  BOOKING_RESCHEDULED: "BOOKING_RESCHEDULED",
  BOOKING_CONFIRMED: "BOOKING_CONFIRMED",
  TECHNICIAN_ASSIGNED: "TECHNICIAN_ASSIGNED",
  BOOKING_STARTED: "BOOKING_STARTED",
  BOOKING_COMPLETED: "BOOKING_COMPLETED",
  BOOKING_CANCELLED: "BOOKING_CANCELLED",
} as const;

export type DomainEventType = (typeof domainEventTypes)[keyof typeof domainEventTypes];
