export const routes = {
  home: "/",
  services: "/services",
  serviceDetail: (slug: string) => `/services/${slug}`,
  ourWork: "/our-work",
  about: "/about",
  contact: "/contact",
  terms: "/terms",
  privacy: "/privacy",
  cookies: "/cookies",
  book: "/book",
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  dashboard: "/dashboard",
  dashboardBookings: "/bookings",
  dashboardBookingDetail: (id: string) => `/bookings/${id}`,
  dashboardInvoices: "/invoices",
  dashboardSettings: "/settings",
  admin: "/admin",
  adminBookings: "/admin/bookings",
  adminBookingDetail: (id: string) => `/admin/bookings/${id}`,
  adminServices: "/admin/services",
  adminTechnicians: "/admin/technicians",
  adminUsers: "/admin/users",
  adminAnalytics: "/admin/analytics",
  adminFeedback: "/admin/feedback",
} as const;
